# 🤖 Khadum AI Webhook Configuration
# All credentials and settings in one YAML file

# WhatsApp Business API Credentials
whatsapp:
  verify_token: "khadum_webhook_verify_token_2024"
  access_token: "EAATfgB4Y7dIBPCRRxSGRCGVvZB8Wzxme7m8fU9jHiZBF49SlWzf7hqcHgZB7w08dYrz2GW2mQSDB7kaCvRsqd2bZCB4j6hFkamkx33tF5tc4JTE7HpbcFknZCMZCctXQVw5wKZBvGdW4Va9NeILGn0rpY95XNE9HhSPeZB1fEvl0ZCNWLVA4wdFQZAfwyHnvKHfqiprgZDZD"
  phone_id: "740099439185588"

# Google Gemini AI Configuration
gemini:
  api_key: "AIzaSyCvR9UpA5fb2NE3hPXalClQECEl_K99J9Y"
  model: "gemini-2.5-flash-lite"
  max_tokens: 500
  temperature: 0.8

# Application Settings
app:
  name: "Khadum AI Webhook"
  version: "1.0.0"
  environment: "production"
  timeout_seconds: 8
  max_conversation_history: 10

# Performance Settings
performance:
  enable_caching: true
  response_timeout: 8000
  max_retries: 2
  enable_fallback: true

# Logging Settings
logging:
  level: "info"
  enable_console: true
  enable_errors: true